version: "3.7"

services:
 caravel-template-api:
   build: .
   ports:
     - "5000:80"
     - "5001:443"
   environment:
     ASPNETCORE_ENVIRONMENT: Development
     DATABASE__CONNECTIONSTRING: "User ID=user;Password=password123;Server=postgres-db;Port=5432;Database=caravel_db;"
   networks:
     - backend
   depends_on:
     - postgres-db

 postgres-db:
   image: postgres:11
   restart: always
   environment:
     POSTGRES_DB: caravel
     POSTGRES_USER: user
     POSTGRES_PASSWORD: password123
   ports:
     - 5432:5432
   volumes:
     - ./data/postgres:/var/lib/postgresql/data
   networks:
     - backend

networks:
  backend: