version: "3.7"

services:
 postgres-db:
   image: postgres:13
   restart: always
   environment:
     POSTGRES_DB: caravel
     POSTGRES_USER: user
     POSTGRES_PASSWORD: password123
   ports:
     - 5432:5432